const STALE_MS = 90_000;
const $ = (id) => document.getElementById(id);
let snapshot; let offline = false; let lastReceived = 0;
const money = (value) => typeof value === 'number' ? new Intl.NumberFormat(undefined, { style:'currency', currency:'USD', maximumFractionDigits:2 }).format(value) : '—';
const text = (node, value) => { node.textContent = value == null || value === '' ? '—' : String(value); };
function recordSnapshot(payload) { const record = payload?.records?.[0]; const raw = record?.data?.snapshot ?? payload?.snapshot ?? payload; return typeof raw === 'string' ? JSON.parse(raw) : raw; }
function setOptions(id, values, label) { const select = $(id); const old = select.value; select.replaceChildren(new Option(label, '')); for (const value of values) select.add(new Option(value, value)); select.value = values.includes(old) ? old : ''; }
function freshness() { const node = $('freshness'); if (!snapshot) { node.className = `status ${offline ? 'offline' : ''}`; text(node, offline ? 'Offline · no snapshot received' : 'Loading snapshot…'); return; } const observed = Date.parse(snapshot.observedAt || ''); const stale = !Number.isFinite(observed) || Date.now() - observed > STALE_MS; node.className = `status ${offline ? 'offline' : stale ? 'stale' : 'live'}`; text(node, offline ? 'Offline · last snapshot retained' : stale ? 'Stale · awaiting publisher' : 'Live snapshot'); text($('updated'), `Observed ${Number.isFinite(observed) ? new Date(observed).toLocaleString() : 'unknown'} · updated ${new Date(lastReceived).toLocaleTimeString()}`); }
function render() { if (!snapshot) return; const workers = Array.isArray(snapshot.workers) ? snapshot.workers : []; const run = snapshot.run || {}; const counts = snapshot.counts || {}; text($('spend'), `${money(run.spendUsd)}${run.spendCapUsd > 0 ? ` / ${money(run.spendCapUsd)}` : ''}`); text($('workers-count'), `${counts.activeWorkers ?? 0} active · ${counts.totalWorkers ?? 0} total`); text($('unknown'), run.unknownCostEvents ?? 0); setOptions('project', [...new Set(workers.map((w) => w.repoSlug).filter(Boolean))].sort(), 'All projects'); setOptions('state', [...new Set(workers.map((w) => w.state).filter(Boolean))].sort(), 'All states'); $('notice').hidden = !counts.truncatedWorkers; text($('notice'), `${counts.truncatedWorkers} older worker${counts.truncatedWorkers === 1 ? '' : 's'} omitted to keep this private snapshot within its size limit.`);
  const project = $('project').value; const state = $('state').value; const filtered = workers.filter((w) => (!project || w.repoSlug === project) && (!state || w.state === state)); const list = $('worker-list'); list.replaceChildren(); if (!filtered.length) { const empty = document.createElement('p'); text(empty, 'No workers match these filters.'); list.append(empty); } for (const worker of filtered) { const card = document.createElement('details'); card.className = 'worker'; const summary = document.createElement('summary'); const left = document.createElement('span'); const name = document.createElement('strong'); text(name, worker.workerId); const meta = document.createElement('span'); meta.className='meta'; text(meta, `${worker.repoSlug || 'unknown project'} · ${worker.model || 'model unknown'}`); left.append(name, document.createElement('br'), meta); const pill = document.createElement('span'); pill.className='pill'; text(pill, worker.state || 'unknown'); summary.append(left, pill); const details = document.createElement('div'); details.textContent = `Role: ${worker.role || '—'}\nElapsed: ${worker.elapsedMs == null ? '—' : `${Math.round(worker.elapsedMs / 1000)}s`}\nSpend: ${money(worker.spendUsd)}\nTokens: ${worker.tokens ?? '—'}\nUpdated: ${worker.updatedAt || '—'}\nHead: ${worker.head || '—'}`; card.append(summary, details); list.append(card); }
  const models = $('models'); models.replaceChildren(); for (const model of snapshot.models || []) { const row = document.createElement('div'); row.className='model'; const a=document.createElement('span'); text(a, model.model); const b=document.createElement('span'); text(b, `${model.active ?? 0} active · ${money(model.spendUsd)}`); row.append(a,b); models.append(row); } freshness(); }
async function load() { if (document.hidden) return; try { const response = await fetch('./.herenow/data/fleet?limit=1', { signal: AbortSignal.timeout(8000), headers:{accept:'application/json'} }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const candidate = recordSnapshot(await response.json()); if (!candidate || typeof candidate !== 'object') throw new Error('invalid snapshot'); snapshot=candidate; offline=false; lastReceived=Date.now(); render(); } catch { offline=true; freshness(); } }
for (const id of ['project','state']) $(id).addEventListener('change', render); document.addEventListener('visibilitychange', () => { if (!document.hidden) load(); }); setInterval(() => { load(); freshness(); }, 30_000); load();
