import type { OperatorSnapshot, SnapshotSource } from "./types.js";

type Dict = Record<string, unknown>;
function dict(value: unknown, name: string): Dict { if (value === null || typeof value !== "object" || Array.isArray(value) || ![Object.prototype, null].includes(Object.getPrototypeOf(value))) throw new Error(`${name} must be a plain object`); return value as Dict; }
function keys(value: Dict, allowed: readonly string[], name: string): void { for (const key of Object.keys(value)) if (!allowed.includes(key)) throw new Error(`${name} contains unknown field ${key}`); }
function stringOrNull(value: unknown, name: string): string | null { if (value !== null && typeof value !== "string") throw new Error(`${name} must be a string or null`); return value as string | null; }
function integerOrNull(value: unknown, name: string): number | null { if (value !== null && (!Number.isSafeInteger(value) || (value as number) < 0)) throw new Error(`${name} must be a non-negative integer or null`); return value as number | null; }
function finiteOrNull(value: unknown, name: string): number | null { if (value !== null && (typeof value !== "number" || !Number.isFinite(value) || value < 0)) throw new Error(`${name} must be a finite non-negative number or null`); return value as number | null; }

export function validateOperatorSnapshot(input: unknown): OperatorSnapshot {
  const value = dict(input, "snapshot"); keys(value, ["schemaVersion", "observedAt", "source", "unknowns", "map", "run", "attempts", "pendingCommands", "needsYou", "resources", "quality"], "snapshot");
  if (value.schemaVersion !== 1 || typeof value.observedAt !== "string" || !Array.isArray(value.unknowns) || value.unknowns.some((item) => typeof item !== "string")) throw new Error("invalid snapshot envelope");
  const source = dict(value.source, "source"); keys(source, ["kind", "evidenceMode", "id", "observedAt"], "source");
  if ((source.kind !== "helm-log" && source.kind !== "fixture") || (source.evidenceMode !== "authoritative" && source.evidenceMode !== "fixture" && source.evidenceMode !== "unknown") || typeof source.id !== "string") throw new Error("invalid source provenance");
  const map = value.map === null ? null : (() => { const row = dict(value.map, "map"); keys(row, ["state", "repository", "parentIssue", "nodes", "frontier", "summary"], "map"); if (!["known", "unknown", "incomplete"].includes(row.state as string)) throw new Error("invalid map state"); stringOrNull(row.repository, "map.repository"); integerOrNull(row.parentIssue, "map.parentIssue"); integerOrNull(row.nodes, "map.nodes"); integerOrNull(row.frontier, "map.frontier"); stringOrNull(row.summary, "map.summary"); return { state: row.state as "known" | "unknown" | "incomplete", repository: row.repository as string | null, parentIssue: row.parentIssue as number | null, nodes: row.nodes as number | null, frontier: row.frontier as number | null, summary: row.summary as string | null }; })();
  const run = dict(value.run, "run"); keys(run, ["runId", "owner", "leases"], "run"); const owner = dict(run.owner, "run.owner"); keys(owner, ["orchestrator", "epoch"], "run.owner"); if (owner.orchestrator !== null && owner.orchestrator !== "fable" && owner.orchestrator !== "astra") throw new Error("invalid owner"); integerOrNull(owner.epoch, "owner.epoch"); const leases = dict(run.leases, "run.leases"); keys(leases, ["orchestrator", "autonomy"], "run.leases");
  const lease = (name: "orchestrator" | "autonomy") => { const row = dict(leases[name], `run.leases.${name}`); keys(row, ["state", "id", "expiresAt"], `run.leases.${name}`); if (!["active", "expired", "revoked", "unknown"].includes(row.state as string)) throw new Error("invalid lease state"); stringOrNull(row.id, "lease.id"); stringOrNull(row.expiresAt, "lease.expiresAt"); return { state: row.state as "active" | "expired" | "revoked" | "unknown", id: row.id as string | null, expiresAt: row.expiresAt as string | null }; };
  const attempts = Array.isArray(value.attempts) ? value.attempts.map((item, index) => { const row = dict(item, `attempts[${index}]`); keys(row, ["attemptId", "mapNodeId", "role", "state", "model", "workspace", "startedAt", "endedAt", "outcome", "epoch"], `attempts[${index}]`); if (typeof row.attemptId !== "string" || (row.mapNodeId !== null && typeof row.mapNodeId !== "string") || typeof row.role !== "string" || typeof row.state !== "string") throw new Error("invalid attempt"); const model = row.model === null ? null : dict(row.model, "attempt.model"); if (model) { keys(model, ["id", "family", "pool"], "attempt.model"); if (typeof model.id !== "string" || typeof model.family !== "string" || typeof model.pool !== "string") throw new Error("invalid model"); } const workspace = row.workspace === null ? null : dict(row.workspace, "attempt.workspace"); if (workspace) { keys(workspace, ["path", "baseSha"], "attempt.workspace"); if (typeof workspace.path !== "string" || typeof workspace.baseSha !== "string") throw new Error("invalid workspace"); } stringOrNull(row.startedAt, "attempt.startedAt"); stringOrNull(row.endedAt, "attempt.endedAt"); stringOrNull(row.outcome, "attempt.outcome"); integerOrNull(row.epoch, "attempt.epoch"); return { attemptId: row.attemptId, mapNodeId: row.mapNodeId as string | null, role: row.role, state: row.state, model: model ? { id: model.id as string, family: model.family as string, pool: model.pool as string } : null, workspace: workspace ? { path: workspace.path as string, baseSha: workspace.baseSha as string } : null, startedAt: row.startedAt as string | null, endedAt: row.endedAt as string | null, outcome: row.outcome as string | null, epoch: row.epoch as number | null }; }) : (() => { throw new Error("attempts must be an array"); })();
  const pendingCommands = Array.isArray(value.pendingCommands) ? value.pendingCommands.map((item, index) => { const row = dict(item, `pendingCommands[${index}]`); keys(row, ["commandId", "kind", "state", "createdAt", "epoch"], `pendingCommands[${index}]`); if (typeof row.commandId !== "string" || typeof row.kind !== "string" || typeof row.state !== "string" || typeof row.createdAt !== "string") throw new Error("invalid command"); integerOrNull(row.epoch, "command.epoch"); return { commandId: row.commandId, kind: row.kind, state: row.state, createdAt: row.createdAt, epoch: row.epoch as number | null }; }) : (() => { throw new Error("pendingCommands must be an array"); })();
  const needsYou = value.needsYou === null ? null : Array.isArray(value.needsYou) ? value.needsYou.map((item, index) => { const row = dict(item, `needsYou[${index}]`); keys(row, ["id", "kind", "summary", "createdAt"], `needsYou[${index}]`); if (typeof row.id !== "string" || typeof row.kind !== "string" || typeof row.summary !== "string" || typeof row.createdAt !== "string") throw new Error("invalid need"); return { id: row.id, kind: row.kind, summary: row.summary, createdAt: row.createdAt }; }) : (() => { throw new Error("needsYou must be an array or null"); })();
  const resources = dict(value.resources, "resources"); keys(resources, ["units", "context"], "resources"); const units = Array.isArray(resources.units) ? resources.units.map((item, index) => { const row = dict(item, `units[${index}]`); keys(row, ["poolId", "unit", "used", "reserved", "limit", "unknown"], `units[${index}]`); if (typeof row.poolId !== "string" || typeof row.unit !== "string") throw new Error("invalid unit"); finiteOrNull(row.used, "unit.used"); finiteOrNull(row.reserved, "unit.reserved"); finiteOrNull(row.limit, "unit.limit"); stringOrNull(row.unknown, "unit.unknown"); return { poolId: row.poolId, unit: row.unit, used: row.used as number | null, reserved: row.reserved as number | null, limit: row.limit as number | null, unknown: row.unknown as string | null }; }) : (() => { throw new Error("units must be an array"); })(); const context = Array.isArray(resources.context) ? resources.context.map((item, index) => { const row = dict(item, `context[${index}]`); keys(row, ["attemptId", "used", "window", "occupancy"], `context[${index}]`); if (typeof row.attemptId !== "string" || (row.occupancy !== "known" && row.occupancy !== "unknown")) throw new Error("invalid context"); integerOrNull(row.used, "context.used"); integerOrNull(row.window, "context.window"); return { attemptId: row.attemptId, used: row.used as number | null, window: row.window as number | null, occupancy: row.occupancy as "known" | "unknown" }; }) : (() => { throw new Error("context must be an array"); })();
  const quality = dict(value.quality, "quality"); keys(quality, ["gate", "integration"], "quality"); const count = (name: "gate" | "integration") => { const row = dict(quality[name], name); keys(row, ["passed", "total"], name); integerOrNull(row.passed, `${name}.passed`); integerOrNull(row.total, `${name}.total`); return { passed: row.passed as number | null, total: row.total as number | null }; };
  stringOrNull(source.observedAt, "source.observedAt");
  return { schemaVersion: 1, observedAt: value.observedAt, source: { kind: source.kind as "helm-log" | "fixture", evidenceMode: source.evidenceMode as "authoritative" | "fixture" | "unknown", id: source.id, observedAt: source.observedAt as string | null }, unknowns: [...value.unknowns] as string[], map, run: { runId: stringOrNull(run.runId, "run.runId"), owner: { orchestrator: owner.orchestrator, epoch: owner.epoch as number | null }, leases: { orchestrator: lease("orchestrator"), autonomy: lease("autonomy") } }, attempts, pendingCommands, needsYou, resources: { units, context }, quality: { gate: count("gate"), integration: count("integration") } };
}
export async function readOperatorSnapshot(source: SnapshotSource): Promise<OperatorSnapshot> { return validateOperatorSnapshot(await source.read()); }
export function formatOperatorJson(snapshot: OperatorSnapshot): string { return `${JSON.stringify(snapshot)}\n`; }
export function formatOperatorCli(snapshot: OperatorSnapshot): string { const owner = snapshot.run.owner.orchestrator ?? "unknown"; const epoch = snapshot.run.owner.epoch === null ? "unknown" : String(snapshot.run.owner.epoch); return [`Observed: ${snapshot.observedAt}`, `Source: ${snapshot.source.id}`, `Run: ${snapshot.run.runId ?? "unknown"}`, `Owner: ${owner} (epoch ${epoch})`, `Attempts: ${snapshot.attempts.length}`, `Pending commands: ${snapshot.pendingCommands.length}`, `Needs you: ${snapshot.needsYou === null ? "unknown" : snapshot.needsYou.length}`, `Unknowns: ${snapshot.unknowns.length}`].join("\n") + "\n"; }
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] as string); }
export function renderOperatorHtml(snapshot: OperatorSnapshot): string {
  const esc = escapeHtml;
  const attempts = snapshot.attempts.map((item) => `<li><strong>${esc(item.attemptId)}</strong><span>${esc(item.state)} · ${esc(item.role)}</span></li>`).join("");
  const needs = snapshot.needsYou === null ? "<li>unknown queue state</li>" : snapshot.needsYou.map((item) => `<li><strong>${esc(item.id)}</strong><span>${esc(item.kind)} · ${esc(item.summary)}</span></li>`).join("");
  const pending = snapshot.pendingCommands.map((item) => `<li><strong>${esc(item.commandId)}</strong><span>${esc(item.kind)} · ${esc(item.state)} · epoch ${item.epoch ?? "unknown"}</span></li>`).join("") || "<li>none observed</li>";
  const map = snapshot.map === null ? "unknown" : `${snapshot.map.state}: ${snapshot.map.nodes ?? "unknown"} nodes · ${snapshot.map.frontier ?? "unknown"} frontier · ${snapshot.map.summary ?? "no summary"}`;
  const lease = (name: "orchestrator" | "autonomy") => { const item = snapshot.run.leases[name]; return `<li><strong>${name}</strong><span>${item.state} · ${item.id ?? "unknown id"} · expires ${item.expiresAt ?? "unknown"}</span></li>`; };
  const units = snapshot.resources.units.map((item) => `<li><strong>${esc(item.poolId)} / ${esc(item.unit)}</strong><span>used ${item.used ?? "unknown"} · reserved ${item.reserved ?? "unknown"} · limit ${item.limit ?? "unknown"}${item.unknown ? ` · ${esc(item.unknown)}` : ""}</span></li>`).join("") || "<li>unknown</li>";
  const context = snapshot.resources.context.map((item) => `<li><strong>${esc(item.attemptId)}</strong><span>${item.occupancy} · tokens ${item.used ?? "unknown"} / window ${item.window ?? "unknown"}</span></li>`).join("") || "<li>unknown</li>";
  const quality = `gate ${snapshot.quality.gate.passed ?? "unknown"}/${snapshot.quality.gate.total ?? "unknown"} · integration ${snapshot.quality.integration.passed ?? "unknown"}/${snapshot.quality.integration.total ?? "unknown"}`;
  const unknowns = snapshot.unknowns.map((item) => `<li>${esc(item)}</li>`).join("") || "<li>none recorded</li>";
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Helm operator</title><style>body{margin:0;background:#f5f7fb;color:#172033;font:15px/1.45 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;gap:16px;align-items:baseline;flex-wrap:wrap}.muted{color:#647089}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.card{background:#fff;border:1px solid #dce2ed;border-radius:10px;padding:16px;box-shadow:0 2px 8px #1720330d}h1{margin:0}h2{font-size:16px;margin:0 0 10px}ul{list-style:none;padding:0;margin:0}li{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid #eef1f6}li:last-child{border-bottom:0}li span{color:#647089;text-align:right}code{background:#edf1f7;border-radius:4px;padding:2px 5px}@media(max-width:600px){main{padding:14px}li{display:block}li span{display:block;text-align:left}}</style></head><body><main><header><h1>Helm operator</h1><span class="muted">observed <code>${esc(snapshot.observedAt)}</code> · ${esc(snapshot.source.evidenceMode)}</span></header><p>Source <code>${esc(snapshot.source.id)}</code> · run <code>${esc(snapshot.run.runId ?? "unknown")}</code> · owner <code>${esc(snapshot.run.owner.orchestrator ?? "unknown")}</code> epoch <code>${snapshot.run.owner.epoch ?? "unknown"}</code></p><section class="grid"><article class="card"><h2>Map</h2><p>${esc(map)}</p></article><article class="card"><h2>Quality</h2><p>${esc(quality)}</p></article><article class="card"><h2>Needs you</h2><ul>${needs}</ul></article><article class="card"><h2>Leases</h2><ul>${lease("orchestrator")}${lease("autonomy")}</ul></article><article class="card"><h2>Attempts</h2><ul>${attempts || "<li>none observed</li>"}</ul></article><article class="card"><h2>Pending commands</h2><ul>${pending}</ul></article><article class="card"><h2>Resources</h2><ul>${units}</ul></article><article class="card"><h2>Context occupancy</h2><ul>${context}</ul></article><article class="card"><h2>Unknowns</h2><ul>${unknowns}</ul></article></section></main></body></html>`;
}
